sudo: false

addons:
  apt:
    packages:
       # Requirements for Brian
    - python-numpy 
    - python-scipy 
    - python-matplotlib 
    - python-sympy
    
language: python

python: 2.7

virtualenv:
    system_site_packages: true

env:
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=jNeuroML_NEURON
    - OMV_ENGINE=PyLEMS_NeuroML2
    - OMV_ENGINE=jNeuroML_Brian
    - OMV_ENGINE=jNeuroML_Brian2

install: 
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation

script:
    - omv all
    
    
    

